---
# assume Ubuntu Server 14.04 (ami-a21529cc)
- hosts: aws
  user: ubuntu
  become: true
  vars_files:
    - vars/secret.yml
    - vars/non_secret.yml
  roles:
    - common
    - rails
    - postgres
    - jenkins
    - nginx